-- Data tablespace
CREATE TABLESPACE minewaste_data
DATAFILE 'minewaste_data01.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- Index tablespace
CREATE TABLESPACE minewaste_index
DATAFILE 'minewaste_index01.dbf' SIZE 50M
AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- Temporary tablespace
CREATE TEMPORARY TABLESPACE minewaste_temp
TEMPFILE 'minewaste_temp01.dbf' SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;
