Table 1: MINE_SITE_MANAGER
CREATE TABLE MINE_SITE_MANAGER (
    MANAGER_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CONTACT VARCHAR2(50) NOT NULL,
    CONSTRAINT chk_manager_contact CHECK (LENGTH(CONTACT) >= 10)
);

-- Table 2: ENVIRONMENTAL_OFFICER
CREATE TABLE ENVIRONMENTAL_OFFICER (
    OFFICER_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CONTACT VARCHAR2(50) NOT NULL,
    CONSTRAINT chk_officer_contact CHECK (LENGTH(CONTACT) >= 10)
);

-- Table 3: RECYCLING_SUPERVISOR
CREATE TABLE RECYCLING_SUPERVISOR (
    SUPERVISOR_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CONTACT VARCHAR2(50) NOT NULL,
    CONSTRAINT chk_supervisor_contact CHECK (LENGTH(CONTACT) >= 10)
);

-- Table 4: MINE_SITE
CREATE TABLE MINE_SITE (
    SITE_ID NUMBER(10) PRIMARY KEY,
    SITE_NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(200),
    MANAGER_ID NUMBER(10),
    CONSTRAINT fk_manager FOREIGN KEY (MANAGER_ID)
    REFERENCES MINE_SITE_MANAGER(MANAGER_ID)
);

-- Table 5: MINE_WASTE
CREATE TABLE MINE_WASTE (
    WASTE_ID NUMBER(10) PRIMARY KEY,
    SITE_ID NUMBER(10) NOT NULL,
    WASTE_TYPE VARCHAR2(100) NOT NULL,
    QUANTITY NUMBER(15,2) NOT NULL,
    DATE_RECORDED DATE DEFAULT SYSDATE NOT NULL,
    IS_RECYCLABLE VARCHAR2(3) DEFAULT 'NO' CHECK (IS_RECYCLABLE IN ('YES', 'NO')),
    CONSTRAINT fk_waste_site FOREIGN KEY (SITE_ID) REFERENCES MINE_SITE(SITE_ID),
    CONSTRAINT chk_quantity CHECK (QUANTITY > 0)
);

-- Table 6: RECYCLING
CREATE TABLE RECYCLING (
    RECYCLING_ID NUMBER(10) PRIMARY KEY,
    WASTE_ID NUMBER(10) NOT NULL,
    SUPERVISOR_ID NUMBER(10) NOT NULL,
    RECYCLED_QUANTITY NUMBER(15,2) NOT NULL,
    RECYCLE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_recycling_waste FOREIGN KEY (WASTE_ID) REFERENCES MINE_WASTE(WASTE_ID),
    CONSTRAINT fk_recycling_supervisor FOREIGN KEY (SUPERVISOR_ID) REFERENCES RECYCLING_SUPERVISOR(SUPERVISOR_ID),
    CONSTRAINT chk_recycled_qty CHECK (RECYCLED_QUANTITY > 0)
);

-- Table 7: WASTE_DISPOSAL
CREATE TABLE WASTE_DISPOSAL (
    DISPOSAL_ID NUMBER(10) PRIMARY KEY,
    WASTE_ID NUMBER(10) NOT NULL,
    OFFICER_ID NUMBER(10) NOT NULL,
    DISPOSAL_METHOD VARCHAR2(100) NOT NULL,
    DISPOSAL_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_disposal_waste FOREIGN KEY (WASTE_ID) REFERENCES MINE_WASTE(WASTE_ID),
    CONSTRAINT fk_disposal_officer FOREIGN KEY (OFFICER_ID) REFERENCES ENVIRONMENTAL_OFFICER(OFFICER_ID)
);

-- Table 8: AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    AUDIT_ID NUMBER(10) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    ACTION_TYPE VARCHAR2(50) NOT NULL,
    INSERT_UPDATE_DELETE VARCHAR2(20),
    TABLE_NAME VARCHAR2(50) NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ALLOWED' CHECK (STATUS IN ('ALLOWED', 'DENIED'))
